services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3333:3333
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  gbshoes-mysql-data:
