services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3333:3333
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - gbshoes-postgres-data:/var/lib/postgres
    environment:
      POSTGRES_DB: gbshoes_db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432

volumes:
  gbshoes-postgres-data:
